name: osv

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "0 8 * * 1"

permissions:
  contents: read

jobs:
  osv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: google/osv-scanner-action/osv-scanner-action@9a498708959aeaef5ef730655706c5a1df1edbc2 # v2.3.8
        with:
          scan-args: |-
            --recursive
            ./
